services:
  web:
    image: webbie/server:latest
    container_name: webbie
    networks:
      - netginx
    expose:
      - "8080"

  api:
    image: api:1.0.1
    container_name: api
    networks:
      - netginx
    expose:
      - "${API_PORT}"

  proxy:
    image: proxie/server
    container_name: proxie
    networks:
      - netginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

networks:
  netginx:
    driver: bridge
