name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
## permission issues, 403 error. 
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v4
#    - name: lint api
#      uses: luke142367/Docker-Lint-Action@v1.0.0
#      with:
#        target: api/Dockerfile
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    - name: Build the api Docker image
      run: docker build api --file api/Dockerfile
    - name: Build the webbie Docker image
      run: docker build nginx --file nginx/Dockerfile
    - name: Build the proxie Docker image
      run: docker build xnign --file xnign/Dockerfile
    - name: check docker-compose for errors
      run: docker-compose config --quiet
      working-directory: compose
    - name: run containers
      run: docker-compose up -d
      working-directory: compose
    - name: test localhost
      run: bash -c "[ 200 == `curl --write-out '%{http_code}' --silent --output /dev/null http://localhost` ]"
    - name: test api-health
      run: bash -c "[ 200 == `curl --write-out '%{http_code}' --silent --output /dev/null http://localhost/api/health` ]"
