name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the api Docker image
      run: docker build api --file api/Dockerfile

    - name: Build the webbie Docker image
      run: docker build nginx --file nginx/Dockerfile

    - name: Build the proxie Docker image
      run: docker build xnign --file xnign/Dockerfile
